#!/usr/bin/env bash
set -euo pipefail

LOG="custom/package-check.log"
: > "$LOG"

# This script MUST NOT select a target. The workflow selects the original
# JDCloud RE-SS-01 target before this script is called.
TARGET_LINE='CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_jdcloud_re-ss-01=y'
if ! grep -qx "$TARGET_LINE" .config; then
  echo 'ERROR: AX1800 Pro target is not selected; refusing to build.' | tee -a "$LOG"
  exit 1
fi

# Refresh package metadata after feeds have been installed.
make defconfig >/dev/null

# Package metadata is generated by OpenWrt after feeds are installed.
META='tmp/.config-package.in'
if [ ! -f "$META" ]; then
  echo "ERROR: $META not found." | tee -a "$LOG"
  exit 1
fi

enable_pkg() {
  local pkg="$1"
  if grep -q "^config PACKAGE_${pkg}$" "$META"; then
    if ! grep -q "^CONFIG_PACKAGE_${pkg}=y$" .config; then
      echo "CONFIG_PACKAGE_${pkg}=y" >> .config
    fi
    echo "ENABLED  $pkg" >> "$LOG"
  else
    echo "MISSING  $pkg" >> "$LOG"
  fi
}

while IFS= read -r pkg || [ -n "$pkg" ]; do
  [[ -z "$pkg" || "$pkg" == \#* ]] && continue
  enable_pkg "$pkg"
done < custom/packages.txt

# Resolve dependencies, remove invalid selections, and preserve the target.
make defconfig >/dev/null

if ! grep -qx "$TARGET_LINE" .config; then
  echo 'ERROR: target changed during package defconfig.' | tee -a "$LOG"
  exit 1
fi

echo '--- final selected packages ---' >> "$LOG"
grep '^CONFIG_PACKAGE_.*=y$' .config >> "$LOG" || true
